class PagesController < ApplicationController
  def runtime_error
    time = Time.now
    foo = "bar" # rubocop:disable Lint/UselessAssignment
    raise "This is a runtime error, generated by the example Rails app at #{time}"
  end
end
